#author	Vladimir Marcin 1-BIT
#email	xmarci10@stud.fit.vutbr.cz
#date	3.3.2017

filename = proj5

all:
	pdflatex $(filename).tex

view:
	evince $(filename).pdf

clean:
		rm -rf 	$(filename).log $(filename).aux $(filename).pdf $(filename).nav $(filename).snm $(filename).toc $(filename).out
	
